### PR TITLE
Version 3.1.7

### PR DESCRIPTION
**Pull request by RouatbiH**

### CODE REVIEW

**Comment by MitanOmar** [comment]
@RouatbiH are you sure about those changes ?

**Comment by MitanOmar** [comment]
@RouatbiH don't do any release to new version, it will broke all servers that have kleeja installed

**Comment by RouatbiH** [comment]
> @RouatbiH are you sure about those changes ?

I'm confident in these changes and have tested them thoroughly. I encourage you to test them yourself as well. If you find any specific issues, please let me know and I'll be happy to address them.

> @RouatbiH don't do any release to new version, it will broke all servers that have kleeja installed

I understand your worry, but I've actually tested this with someone who has a huge database. Everything worked perfectly. I'm confident it won't break existing installations.

**Comment by MitanOmar** [comment]
@RouatbiH  currently kleeja running on PHP 7.4, if you do a release now for version PHP 8, all kleeja servers that are running kleeja on php version 7.4, will stop

in the beginning, you have to make a change in kleeja, to stop kleeja from upgrading if the PHP version is less then PHP8

and after that, you can push all those changes, so only the servers that have PHP 8, will upgrade to the next version that i compatible with the new changes

**Comment by RouatbiH** [comment]
> @RouatbiH currently kleeja running on PHP 7.4, if you do a release now for version PHP 8, all kleeja servers that are running kleeja on php version 7.4, will stop
> 
> in the beginning, you have to make a change in kleeja, to stop kleeja from upgrading if the PHP version is less then PHP8
> 
> and after that, you can push all those changes, so only the servers that have PHP 8, will upgrade to the next version that i compatible with the new changes

The code still supports PHP 7 until 8.3. We haven't dropped PHP 7 support. If you want, we can add a check to only allow upgrades for PHP 8+. Let me know if you'd like that added.

**Pull request merged**
