### PR TITLE
Update style.php

### PR DESCRIPTION
**Pull request by munjoob**
check if caching is not enabled and empty style cache files only to keep kleeja log file for development needs instead of emptying all cache folder from cp.

### CODE REVIEW

**Comment by abdumu** [comment]
Thanks for your contribution.

I added some comments, review them.

**Comment by munjoob** [comment]
yes ok

**Comment by munjoob** [comment]
this is faster and not delete kleeja log file

**Comment by abdumu** [comment]
We can change delete_cache to ignore the log file.

**Comment by munjoob** [comment]
i used delete_cache no more changes is needed

**Comment by abdumu** [comment]
if we want to keep the log, we have to change functions.php

**Comment by munjoob** [comment]
as you do this will delete kleeja log file

**Comment by munjoob** [comment]
we realy need that because cachingis disabled in development mode
an developer need log file
what i did was more simple
keep them

**Comment by munjoob** [comment]
kleeja log must not deleted only on development mode 
not on general case like "index.html"

**Comment by munjoob** [comment]
if you keep what i do first it is more easy ...

**Comment by abdumu** [comment]
Change functions.php directly and add `kleeja.log` there to the exceptions array, and remove the exceptions and `global` thing from style and it will be ready.

**Comment by munjoob** [comment]
no if then admin want to remove from cp he can not remove kleeja log
kleeja log can not exluded in general
only in caching disabled mode
do you understand me?

**Comment by munjoob** [comment]
if you keep what i do first it will remove style cache without kleeja log in disabled mode
because disable caching using by developer

**Pull request merged**
